import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Upload, Play, Pause, Download, Settings2, Plus, Trash2, RefreshCw, Music2 } from 'lucide-react';
import './styles.css';

type Word = { text: string; time: number };
type Line = { text: string; time: number; confidence: number; words?: Word[] };
type Meta = { ar: string; ti: string; al: string; by: string; offset: string };
const defaults = { hue: 55, sat: 35, bright: 55, white: 80, minArea: 0.4, sample: 4 };
const demo: Line[] = [
  { text: 'Demo mode — add your lyrics below', time: 3.2, confidence: 100 },
  { text: 'Kareoketo follows the video timeline', time: 7.8, confidence: 100 },
  { text: 'Edit these lines or analyze a karaoke video', time: 12.4, confidence: 100 }
];
function fmt(s:number){const m=Math.floor(Math.max(0,s)/60);return `[${String(m).padStart(2,'0')}:${(Math.max(0,s)%60).toFixed(2).padStart(5,'0')}]`}
function App(){
 const videoRef=useRef<HTMLVideoElement>(null); const canvasRef=useRef<HTMLCanvasElement>(null); const [file,setFile]=useState<File|null>(null); const [url,setUrl]=useState(''); const [lines,setLines]=useState<Line[]>(demo); const [meta,setMeta]=useState<Meta>({ar:'',ti:'',al:'',by:'',offset:'0'}); const [settings,setSettings]=useState(defaults); const [showSettings,setShowSettings]=useState(false); const [playing,setPlaying]=useState(false); const [time,setTime]=useState(0); const [analyzing,setAnalyzing]=useState(false); const [progress,setProgress]=useState(0); const [error,setError]=useState('');
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 const active=useMemo(()=>{let i=-1; lines.forEach((l,n)=>{if(l.time<=time)i=n});return i},[lines,time]);
 function pick(f:File){setError(''); if(!f.type.startsWith('video/')){setError('Please choose a browser-decodable video (MP4/H.264 or WebM are recommended).');return} setFile(f);setUrl(URL.createObjectURL(f));setLines([]);}
 function analyze(){ if(!videoRef.current||!file){setError('Select a video first.');return} setError('');setAnalyzing(true);setProgress(0); const v=videoRef.current; const c=canvasRef.current!; const ctx=c.getContext('2d',{willReadFrequently:true})!; const duration=v.duration||0; const sample=Math.max(1,settings.sample); let t=0; const candidates:number[]=[]; const scan=()=>{if(t>duration){finish(candidates,duration);return} v.currentTime=t; const on=()=>{c.width=320;c.height=Math.max(180,Math.round(320*v.videoHeight/v.videoWidth));ctx.drawImage(v,0,0,c.width,c.height);const d=ctx.getImageData(0,0,c.width,c.height).data;let yellow=0,white=0;for(let i=0;i<d.length;i+=16){const r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?((mx-mn)/mx)*100:0,h=(Math.atan2(Math.sqrt(3)*(g-b),2*r-g-b)*180/Math.PI+360)%360;if((h<settings.hue||h>360-settings.hue)&&sat>settings.sat&&mx>settings.bright)yellow++;if(r>settings.white*2.55&&g>settings.white*2.55&&b>settings.white*2.55)white++;} if(yellow>white*0.05&&yellow>80)candidates.push(t);progress(Math.min(99,t/duration*100));t+=sample;scan()};v.addEventListener('seeked',on,{once:true})};scan(); }
 function progress(p:number){setProgress(Math.round(p))}
 function finish(c:number[],duration:number){const groups:number[]=[];c.forEach(t=>{if(!groups.length||t-groups[groups.length-1]>2)groups.push(t)});const out=groups.slice(0,200).map((t,i)=>({text:`Detected lyric line ${i+1}`,time:t,confidence:Math.min(96,55+Math.round((c.filter(x=>x>=t&&x<t+2).length)*8))}));if(!out.length){setError('No convincing white/yellow karaoke transition was detected. Try Advanced settings or a video with white → yellow lyric highlighting.')}setLines(out);setProgress(100);setAnalyzing(false)}
 function download(){const body=[`[ar:${meta.ar}]`,`[ti:${meta.ti}]`,`[al:${meta.al}]`,`[by:${meta.by}]`,`[offset:${meta.offset}]`,'',...lines.sort((a,b)=>a.time-b.time).map(l=>fmt(l.time)+l.text)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));a.download=((file?.name||'karaoke').replace(/\.[^.]+$/,'')+'.lrc');a.click()}
 function updateLine(i:number,key:keyof Line,value:string){setLines(x=>x.map((l,n)=>n===i?{...l,[key]:key==='time'||key==='confidence'?Number(value):value}:l))}
 return <main><header><div className="brand"><Music2/> <span>Kareoketo <b>LRC</b></span></div><div className="privacy">Your video is processed locally in your browser and is not uploaded.</div></header>
 <section className="hero"><div><h1>Karaoke video → synchronized LRC</h1><p>Detect lyric highlighting, verify timing, edit mistakes, and export a player-friendly lyric file.</p></div><button className="secondary" onClick={()=>setShowSettings(!showSettings)}><Settings2 size={17}/> Advanced</button></section>
 {showSettings&&<section className="panel settings"><h3>Analysis settings</h3><div className="grid">{([['hue','Yellow hue tolerance',0,180],['sat','Saturation threshold',0,100],['bright','Brightness threshold',0,100],['white','White brightness',0,100],['minArea','Minimum text area',0,10],['sample','Frame sampling (sec)',0.5,10]] as const).map(([k,label,min,max])=><label key={k}>{label}<input type="number" min={min} max={max} step="0.5" value={settings[k]} onChange={e=>setSettings(s=>({...s,[k]:Number(e.target.value)}))}/></label>)}</div></section>}
 <section className="panel uploader" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)pick(f)}}><Upload size={30}/><h2>{file?file.name:'Drop a karaoke video here'}</h2><p>MP4/H.264 and WebM are recommended. MOV/MKV depend on browser decoding support.</p><label className="primary">Choose video<input hidden type="file" accept="video/*" onChange={e=>{const f=e.target.files?.[0];if(f)pick(f)}}/></label>{file&&<div className="filemeta">{videoRef.current?.videoWidth||'—'} × {videoRef.current?.videoHeight||'—'} · {file.size>1048576?(file.size/1048576).toFixed(1)+' MB':Math.round(file.size/1024)+' KB'}</div>}</section>
 {error&&<div className="error">{error}</div>}
 <section className="panel analyze"><div><h2>1. Analyze lyrics</h2><p>Frame sampling looks for lyric-shaped white/yellow transitions instead of treating every yellow pixel as a lyric.</p></div><button className="primary" disabled={!file||analyzing} onClick={analyze}>{analyzing?<><RefreshCw className="spin" size={17}/> Analyzing {progress}%</>:<>Analyze Lyrics</>}</button>{analyzing&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}</section>
 <section className="panel meta"><h2>2. LRC metadata</h2><div className="grid">{([['ar','Artist'],['ti','Title'],['al','Album'],['by','Album Artist'],['offset','Offset']] as const).map(([k,l])=><label key={k}>{l}<input value={meta[k]} onChange={e=>setMeta(m=>({...m,[k]:e.target.value}))}/></label>)}</div></section>
 <section className="verify"><div className="videoCol panel"><h2>Original video</h2>{url?<video ref={videoRef} src={url} controls onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onLoadedMetadata={()=>setTime(0)}/>:<div className="videoPlaceholder"><Music2 size={40}/><span>Video preview</span></div>}<canvas ref={canvasRef} hidden/><button className="download" onClick={download} disabled={!lines.length}><Download size={17}/> Download LRC</button></div>
 <div className="caption panel"><h2>Reconstructed captions</h2><div className="captionStage">{lines.length?lines.map((l,i)=><div key={i} className={`captionLine ${i===active?'active':''} ${i<active?'past':''}`}>{l.text}</div>):<div className="empty">Analyze a video to reconstruct its lyric timeline.</div>}</div><div className="captionControls"><button className="secondary" onClick={()=>videoRef.current?.play()}><Play size={15}/></button><button className="secondary" onClick={()=>videoRef.current?.pause()}><Pause size={15}/></button><span>{fmt(time).slice(1,-1)} · {playing?'Playing':'Paused'}</span></div></div></section>
 <section className="panel editor"><div className="editorHead"><div><h2>3. Manual correction</h2><p>Changes immediately affect preview and exported LRC.</p></div><button className="secondary" onClick={()=>setLines(x=>[...x,{text:'New lyric line',time:x.length?x[x.length-1].time+3:0,confidence:100}])}><Plus size={16}/> Add line</button></div>{lines.map((l,i)=><div className="row" key={i}><input className="time" type="number" step="0.01" value={l.time} onChange={e=>updateLine(i,'time',e.target.value)}/><input value={l.text} onChange={e=>updateLine(i,'text',e.target.value)}/><span className={l.confidence>=80?'good':l.confidence>=60?'mid':'low'}>{l.confidence}%</span><button className="icon" onClick={()=>setLines(x=>x.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div>)}</section>
 <footer>Heuristic detection • Local-only processing • Best results with white → yellow karaoke highlighting</footer></main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
